<?php
/*
 * Copyright (c) 2007 PHPMyFrameWork - Joao Pinto
 * AUTHOR: Joao Paulo Lopes Pinto -- http://jplpinto.com
 * 
 * The use of this code must be allowed first by the creator Joao Pinto, since this is a private and proprietary code.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS 
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER 
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

$UserAuthenticationHandler->checkPresentationFileAuthentication($entity_path, "access"); $popup = $_GET["popup"]; $tutorials = getTutorials(); function getTutorials() { return array( "1_1_simple_setup" => array( "title" => "Lesson 1.1 - Simple Setup", "description" => "This video explains how you can execute a step by step installation of the framework, but you only need to execute the following steps if you downloaded the raw version of the CMS.<br/>
			Note: We configured the 'localhost:81' virtual host to point to the root folder of the framework, but this is optional...", "image" => "", "video" => "https://www.youtube.com/embed/ePEKhVf4qUo", ), "1_2_advanced_setup" => array( "title" => "Lesson 1.2 - Advanced Setup", "description" => "This video explains how you can execute a step by step installation of the framework in companies with multiple IT departments and multiple sites, but you only need to execute the following steps if you downloaded the raw version of the rfamework, otherwise you can change the layers according with your needs in the 'Layers Panel' of the 'Advanced Admin Panel'.<br/>
			Note: We configured the 'localhost:81' virtual host to point to the root folder of framework, but this is optional...", "image" => "", "video" => "https://www.youtube.com/embed/rjFNByM0bJI", ), "1_3_module_installation" => array( "title" => "Lesson 1.3 - Modules Installation", "description" => "After the framework configured, you should install the modules that fulfill your needs, in order to create pages very fast and easily. This video explains how to do this..<br/>
			Note that the modules installation is optional and you only need to do it if you wish to have a wyswyg and no-code UI and use the Template-Region-Block relationship to create pages. Otherwise you can still create pages through our basic system, which is very user-friendly too...", "image" => "", "video" => "https://www.youtube.com/embed/93bSFSmzmro", ), "1_4_manage_user_perms" => array( "title" => "Lesson 1.4 - User Permissions Management", "description" => "In this video you can learn to create users and groups and give them permissions to access certain files in the framework.<br/>
			This allows multiple departments working together with different access levels, this is, the developers can have access to all files in the framework, but the webdesigners only to the Presentation/Interface Layer.<br/>
			Additionally when you install a new module, you must edit the correspondent permissions to the modules' files, otherwise you won't be able to access them.", "image" => "", "video" => "https://www.youtube.com/embed/9HB_hHuOY8c", ), "2_1_1_creation_of_simple_page_on_simple_admin" => array( "title" => "Lesson 2.1.1 - Create Simple Page - on Simple Admin UI", "description" => "This video explains how to create a simple Page with a simple text. Basically we will create a Page with some dummy text.", "image" => "", "video" => "https://www.youtube.com/embed/uhkSijyV_5Y", ), "2_1_2_creation_of_simple_page_with_template_on_simple_admin" => array( "title" => "Lesson 2.1.2 - Create Simple Page with Template - on Simple Admin UI", "description" => "This video explains how to create a Page which will be integrated into a pre-installed Template. Basically we will create a Page and set a variable inside of that Page and then print that variable through the Template.<br/>
			In these examples you must be familiar with creating and print variables in php.", "image" => "", "video" => "https://www.youtube.com/embed/f3JHcptQ3h4", ), "2_1_3_creation_of_simple_page_with_modules_on_simple_admin" => array( "title" => "Lesson 2.1.3 - Create Simple Page with Modules - on Simple Admin UI", "description" => "This video explains how to create a Page using the Page Simple UI which uses pre-installed Templates and Modules.
 In this example we will use the 'Menu' Module to create a menu and the 'EchoStr' Module to show some text in the Main Area of the template. The purpose of this video is to teach how pages can be used with templates and modules.", "image" => "", "video" => "https://www.youtube.com/embed/uCG2_JeAP6k", ), "2_2_1_creation_of_simple_page_on_advanced_admin" => array( "title" => "Lesson 2.2.1 - Create Simple Page - on Advanced Admin UI", "description" => "This video explains how to create a simple Page with a simple html text. Basically we will create a Page with some dummy html.", "image" => "", "video" => "https://www.youtube.com/embed/aH2ZXe9gIGI", ), "2_2_2_1_creation_of_simple_page_with_view_on_advanced_admin_1" => array( "title" => "Lesson 2.2.2.1 - Create Simple Page with View - on Advanced Admin UI", "description" => "This video explains how to create a Page with a View with a simple text.<br/>
			Explains how can you use a View in multiple Pages, this is, you can use Views to display data coming from Pages, reusing code instead of repeating it...<br/>
			In these examples you must be familiar with creating and print variables in php.", "image" => "", "video" => "https://www.youtube.com/embed/a83yXdijUL0", ), "2_2_2_2_creation_of_simple_page_with_view_on_advanced_admin_2" => array( "title" => "Lesson 2.2.2.2 - Create Simple Page with View - on Advanced Admin UI", "description" => "This video explains how to create a Page with a View with a simple text. Explains how can you have Pages with php variables and php logic code, and Views with html code.<br/>
			In these examples you must be familiar with creating and print variables in php.", "image" => "", "video" => "https://www.youtube.com/embed/URZZuNQ7HS0", ), "2_2_3_creation_of_simple_page_with_template_on_advanced_admin" => array( "title" => "Lesson 2.2.3 - Create Simple Page with Template - on Advanced Admin UI", "description" => "This video explains how to create a Page which will be integrated into a pre-installed Template. Basically we will create a page and set a variable inside of that page and then print that variable through the template.<br/>
			In these examples you must be familiar with creating and print variables in php.", "image" => "", "video" => "https://www.youtube.com/embed/ueHwYCIrPlM", ), "2_2_4_creation_of_simple_page_with_view_and_template_on_advanced_admin" => array( "title" => "Lesson 2.2.4 - Create Simple Page with View and Template - on Advanced Admin UI", "description" => "This video explains how to create a Page with a View but that will be integrated into a pre-installed Template.<br/>
			Basically we will create a Page which will call a View and then print the view throught a Template. The View will create the html according with the variables defined in the Page.<br/> 
			In these examples you must be familiar with creating and print variables in php.", "image" => "", "video" => "https://www.youtube.com/embed/GLb9lPYJE1g", ), "2_2_5_creation_of_simple_page_with_modules_on_advanced_admin" => array( "title" => "Lesson 2.2.5 - Create Simple Page with Modules - on Advanced Admin UI", "description" => "This video explains how to create a Page using the Page Simple UI which uses pre-installed Templates and Modules. In this example we will use the 'Menu' Module to create a menu and the 'EchoStr' Module to show some text in the Main Area of the template.<br/> 
			The purpose of this video is to teach how pages can be used with templates and modules.", "image" => "", "video" => "https://www.youtube.com/embed/j1s2Qcl1po0", ), "3_1_creation_of_simple_site_with_modules_integration" => array( "title" => "Lesson 3.1 - Create a Simple Site using the default DB and pre-installed Modules", "description" => "This video explains how to create a simple site in the framework, with a homepage, a list of articles and another page to see each article individually.<br/> 
			Learn how to create simple sites by creating basic templates and configure pre-installed modules.<br/>
			The purpose of these videos is to teach you how templates and regions, modules and blocks work and how can be integrated into pages.", "image" => "", "video" => "https://www.youtube.com/embed/ir8WAnVi5Cg", ), "3_2_1_creation_of_db_diagram" => array( "title" => "Lesson 3.2.1 - Create DB Tables Diagram and Reverse Engineering", "description" => "This video explains how to create a DataBase diagram, generate the correspondent SQL and insert it to a DB.<br/>
			Additionally shows how to reverse engineering a schema from a DataBase into a tables diagram.", "image" => "", "video" => "https://www.youtube.com/embed/__FeuikKvUI", ), "3_2_2_1_creation_of_ibatis" => array( "title" => "Lesson 3.2.2.1 - Create Queries through Ibatis", "description" => "This video explains how to create SQL queries through our CMS or configure the Data-access objects to a Data-base Table.<br/>
			Additionally it shows how to create these rules automatically from a DataBase diagram. Basically the framework will generate automatically the rules from a DataBase diagram, saving time to the programmer and maximizing his work...", "image" => "", "video" => "https://www.youtube.com/embed/xib4OKTdjY0", ), "3_2_2_2_creation_of_hbn" => array( "title" => "Lesson 3.2.2.2 - Create Objects through Hibernate", "description" => "This video explains how to create objects through the HIBERNATE system.
Additionally it shows how to create these objects automatically from a DataBase diagram.<br/>
			Basically the framework will generate automatically the objects from a DataBase diagram, saving time to the programmer and maximizing his work...", "image" => "", "video" => "https://www.youtube.com/embed/PhJMowYIuF8", ), "3_2_2_3_ibatis_and_hbn_xml_files" => array( "title" => "Lesson 3.2.2.3 - Ibatis and Hibernate XML Files", "description" => "This video shows that you can edit directly the XML files of Ibatis and Hibernate in case you don't like to do it via the simple UI of the framework... Explains how to create SQL queries and Hibernate Objects directly in the xml file.", "image" => "", "video" => "https://www.youtube.com/embed/8057YRW73ss", ), "3_2_3_creation_of_soa" => array( "title" => "Lesson 3.2.3 - Create a Service in the Business Logic Layer", "description" => "This video explains how to create a Service in the Business Logic Layer and relate it to the data-access layer.<br/>
			Additionally it shows how to create these services automatically from SQL queries and objects in the Data-Access Layer. Basically the framework will generate automatically the services from the rules of a Data-Access Layer, saving time to the programmer and maximizing his work...<br/>
			Note that if the Business-Logic Layer is connected directly to the Data-Base Layer, it can execute sql directly too, but this explanation is not in this video.", "image" => "", "video" => "https://www.youtube.com/embed/pEPOW0HfueE", ), "3_2_4_1_1_prepare_presentation_page_calling_business_logic_with_files_diagram" => array( "title" => "Lesson 3.2.4.1.1 - Create Page via Files Diagram - SOA - on Advanced Admin UI", "description" => "This video explains how to create a page which calls a service from the Business Logic Layer... It shows that is possible to call a service from the Business Logic Layer through Files Diagram very easy and fast.", "image" => "", "video" => "https://www.youtube.com/embed/M5vIbTZbXJ8", ), "3_2_4_1_2_prepare_presentation_page_calling_ibatis_and_hibernate_with_files_diagram" => array( "title" => "Lesson 3.2.4.1.2 - Create Page via Files Diagram - Ibatis+Hibernate - on Advanced Admin UI", "description" => "This video explains how to create a page which calls a service from Ibatis and Hibernate Layers... It shows that is possible to call a service from Data-Access Layers through the Files Diagram very easy and fast.", "image" => "", "video" => "https://www.youtube.com/embed/rob3F-7Eivo", ), "3_2_4_2_1_prepare_presentation_page_calling_business_logic_with_form_module" => array( "title" => "Lesson 3.2.4.2.1 - Create Page via Form Module - SOA - on Advanced Admin UI", "description" => "This video explains how to create a page which calls a service from the Business Logic Layer... It shows that is possible to call a service from the Business Logic Layer through the 'Form' Module.", "image" => "", "video" => "https://www.youtube.com/embed/sCQr-3FULJA", ), "3_2_4_2_2_prepare_presentation_page_calling_ibatis_and_hibernate_with_form_module" => array( "title" => "Lesson 3.2.4.2.2 - Create Page via Form Module - Ibatis - on Advanced Admin UI", "description" => "This video explains how to create a page which calls a service from Ibatis and Hibernate Layers... It shows that is possible to call a service from Data-Access Layers through the 'Form' Module.", "image" => "", "video" => "https://www.youtube.com/embed/2pu9qoost-Y", ), "3_2_4_2_3_prepare_presentation_page_using_form_module_wizard" => array( "title" => "Lesson 3.2.4.2.3 - Create Page via Form Module - Wizard - on Advanced Admin UI", "description" => "This video explains how to create a page with DB Table list through the Wizard of the 'Form' Module.<br/>
			Note that in order to use this wizard the Presentation Layers must be directly connected to a Data-Access Layer.", "image" => "", "video" => "https://www.youtube.com/embed/G5wy8cyJffE", ), "3_2_4_2_4_prepare_presentation_page_using_form_module_workflow" => array( "title" => "Lesson 3.2.4.2.4 - Create Page via Form Module - Workflow - on Advanced Admin UI", "description" => "This video explains how to create a page with DB Table list by drag & dropping through the Workflow of the 'Form' Module.", "image" => "", "video" => "https://www.youtube.com/embed/Iq7HgVuFau8", ), "3_2_4_2_5_1_conversion_of_form_settings_to_ptl" => array( "title" => "Lesson 3.2.4.2.5.1 - Conversion of Form Settings to PTL - on Advanced Admin UI", "description" => "Our Html template language is a proprietary language called: PTL - PHP Template Language - which allows you to write logic code inside of the html.<br/>
			Is very fast and user-friendly!!!<br/>
			This video explains how to convert a Form settings to a HTML template language in the framework...", "image" => "", "video" => "https://www.youtube.com/embed/nuuA6GFazkY", ), "3_2_4_2_5_2_conversion_of_form_settings_to_ptl" => array( "title" => "Lesson 3.2.4.2.5.2 - Conversion of Form Settings to PTL - on Advanced Admin UI", "description" => "Our Html template language is a proprietary language called: PTL - PHP Template Language which allows you to write logic code inside of the html.<br/>
			Is very fast and user-friendly!!!<br/>
			This video explains how to convert a Form settings to a HTML template language in the framework...", "image" => "", "video" => "https://www.youtube.com/embed/j5FJXWX6OyM", ), "3_2_4_2_5_3_conversion_of_form_settings_to_ptl" => array( "title" => "Lesson 3.2.4.2.5.3 - Conversion of Form Settings to PTL - on Advanced Admin UI", "description" => "Our Html template language is a proprietary language called: PTL - PHP Template Language which allows you to write logic code inside of the html.<br/>
			Is very fast and user-friendly!!!<br/>
			This video explains how to convert a Form settings to a HTML template language in the framework...", "image" => "", "video" => "https://www.youtube.com/embed/pjCOpAqapG0", ), "3_2_4_2_6_1_creation_of_excel_reports" => array( "title" => "Lesson 3.2.4.2.6.1 - Creation of Excel Reports - on Advanced Admin UI", "description" => "This video teaches how to create Excel reports in only a few minutes, based in meta-data from a Data-Base...
", "image" => "", "video" => "https://www.youtube.com/embed/9h7vNkAZohQ", ), "3_2_4_3_creation_of_page_with_business_logic_via_workflow" => array( "title" => "Lesson 3.2.4.3 - Create a Page via Workflow with SOA - on Advanced Admin UI", "description" => "This video explains how to create a page in the framework, which calls a service from the Business Logic Layer...
It shows that is possible to call a service from the Business Logic Layer through a Workflow UI by drag-and-drop or directly by code.<br/>
			Note that it is possible to create back-office interfaces automatically from services of the Business Logic Layer. Basically the framework will generate automatically the interfaces from the services of a Business Logic Layer, saving time to the programmer and maximizing his work... However this example is not shown in this video.<br/>
			Note that if the Presentation is directly connected to the Data-Access Layer, it can execute the correspondent queries and objects directly without passing through the Business Logic Layer.<br/>
			Or if it is directly connected with the Data-Base Layer, it can execute sql directly too, but neither of these explanations are in this video.", "image" => "", "video" => "https://www.youtube.com/embed/fDdsI-iMcRk", ), "4_1_template_installation_and_creation_of_simple_template_with_modules_integration" => array( "title" => "Lesson 4.1 - Install a Template", "description" => "This video explains how to install a template into a project and then related that template with a page and the blocks with the correspondent regions...<br/>
			Note that the purpose of this video is to teach you how to install templates, so we created a very basic template with few HTML tags, very basic css and raw layout.", "image" => "", "video" => "https://www.youtube.com/embed/bORyhC9Q1l4", ), "4_2_creation_of_simple_template_with_modules_integration" => array( "title" => "Lesson 4.2 - Create a Template", "description" => "This video explains how to create a template with regions and then related that template with a page and the blocks with the correspondent regions...<br/>
			The template in this video is a very basic template with few HTML tags, very basic css and raw layout, in order to teach you how to integrate template-regions and modules-blocks into a page.", "image" => "", "video" => "https://www.youtube.com/embed/NkEFNv_bAX4", ), "4_3_1_creation_of_beautiful_layouts_and_templates" => array( "title" => "Lesson 4.3.1 - Create Nice Layouts and Templates", "description" => "This video shows how to design nice layouts through our 'Layout UI Editor' and convert them into usable multi-region templates so that they can be used as a page template when creating pages.", "image" => "", "video" => "https://www.youtube.com/embed/WWkvs_h4dSA", ), "5_1_creation_of_back_office_without_authentication" => array( "title" => "Lesson 5.1 - Create a full Back-Office without Authentication", "description" => "The video bellow shows how to create a full admin panel to manage your DB tables based on a schema, this is, based on a Data-Base diagram the framework will build all the necessary sql queries, then the business logic services and for last, the admin layouts, allowing you to manage your Data-Base without programming a single line of code.<br/>
			Create a full back-office without authentication, where everyone can access it. All users have the same permissions and can execute all actions...<br/>
			After this, switch the layouts across 4 different templates or change them directly accordingly with your needs...", "image" => "", "video" => "https://www.youtube.com/embed/b0125JFb5Ug", ), "5_2_1_creation_of_back_office_with_authentication" => array( "title" => "Lesson 5.2.1 - Create a full Back-Office with Authentication and Permissions 1", "description" => "This video shows how to create a full admin panel to manage your DB tables based on a schema, this is, based on a Data-Base diagram the framework will build all the necessary sql queries, then the business logic services and for last, the admin layouts, allowing different users to manage your DB schema depending the permissions you set to them...<br/>
			Create or change a full back-office with user authentication, where users can have different permissions, access different things and execute different actions...<br/>
			After this, switch the layouts across 4 different templates or change them directly accordingly with your needs...", "image" => "", "video" => "https://www.youtube.com/embed/_rvxojrzVZs", ), "5_3_1_change_existent_back_office_layouts_1" => array( "title" => "Lesson 5.3.1 - Change Existent Back-Office Layouts 1", "description" => "This video shows how to manage existent layouts by drag and dropping boxes in our Files Diagram UI.<br/>
			As it shows in the video bellow, you can change the users permissions for it's page, draw lists and forms for specific tables, define which actions the user can do, connect multiple files by drag and dropping, list data from a table which is children or parent of another...", "image" => "", "video" => "https://www.youtube.com/embed/rx3y8IrL6oE", ), "5_3_2_change_existent_back_office_layouts_2" => array( "title" => "Lesson 5.3.2 - Change Existent Back-Office Layouts 2", "description" => "This video shows how to manage existent layouts by drag and dropping boxes in our Files Diagram UI.<br/>
			As it shows in the video bellow, you can change the users permissions for it's page, draw lists and forms for specific tables, define which actions the user can do, connect multiple files by drag and dropping, list data from a table which is children or parent of another...", "image" => "", "video" => "https://www.youtube.com/embed/3vx-6nL1JFs", ), "5_4_add_db_table_and_back_office_page" => array( "title" => "Lesson 5.4 - Add DB Table and Back-Ofice Page", "description" => "This video teaches how to create a new table in your Data-Base and then create a new page based in our 'Files Diagram UI' via drag-and-drop.<br/>
			We will show how to create different types of Lists and Forms and multiple ways of showing and connect them with other pages...", "image" => "", "video" => "https://www.youtube.com/embed/DKc5KK7Jp2o", ), "5_5_create_new_backoffice_manually_from_scratch" => array( "title" => "Lesson 5.5 - Create New Back-Office Manually from scratch", "description" => "The video bellow teaches how to create from scratch new Back-Office's pages, this is, how to create in a few minutes new pages with lists and forms to view and edit Data-Base meta-data.<br/>
			Basically we will create 3 new pages:<br/>
			- Index page: which will be the home-page with the links to the other pages.<br/>
			- Schools page: which will contain the list of all schools. In this list you can edit or delete the existent schools or add new ones.<br/>
			- School's Teachers page: which will contain the list of teachers for a specific school. In this list you can edit or delete the existent teachers or add new ones.", "image" => "", "video" => "https://www.youtube.com/embed/ieaXBMZavDQ", ), "6_1_installation_of_wordpress_instances" => array( "title" => "Lesson 6.1 - Installation of WordPress instances", "description" => "The video bellow teaches how to install WordPress instances so you can integrate the WordPress' features into your pages in the framework. You can learn how to do this in the next lesson...", "image" => "", "video" => "https://www.youtube.com/embed/KbBYDIKMIpo", ), "6_2_creation_of_simple_page_with_wordpress_features" => array( "title" => "Lesson 6.2 - Creation of a simple page with some WordPress features", "description" => "The video bellow teaches how to create a simple page and integrate some WordPress features in it, like incorporate individual WordPress menus, sidebars, widgets, sub-pages and other contents...", "image" => "", "video" => "https://www.youtube.com/embed/rNtgD4hCNqs", ), "6_3_creation_of_simple_page_with_wordpress_templates" => array( "title" => "Lesson 6.3 - Creation of a simple page using WordPress templates", "description" => "The video bellow teaches how to create a simple page using WordPress templates and pages and then add new content to these templates...", "image" => "", "video" => "https://www.youtube.com/embed/_Fhf8OIzb2Y", ), ); } ?>
