<?php
/*
 * Copyright (c) 2007 PHPMyFrameWork - Joao Pinto
 * AUTHOR: Joao Paulo Lopes Pinto -- http://jplpinto.com
 * 
 * The use of this code must be allowed first by the creator Joao Pinto, since this is a private and proprietary code.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS 
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER 
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. IN NO EVENT SHALL 
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

function get_lib($v327f72fb62, $v3fb9f41470 = "php") { $v30857f7eca = get_lib_settings($v327f72fb62); return $v30857f7eca[0] . str_replace(".", "/", $v30857f7eca[1] ) . "." . $v3fb9f41470; } function get_lib_settings($v327f72fb62) { $v8a4df75785 = strpos($v327f72fb62, "."); $v375507cc94 = substr($v327f72fb62, 0, $v8a4df75785); $v9643d970d1 = ""; switch(strtolower($v375507cc94)) { case "lib": $v9643d970d1 = LIB_PATH; break; case "app": $v9643d970d1 = APP_PATH; break; case "vendor": $v9643d970d1 = VENDOR_PATH; break; case "root": $v9643d970d1 = CMS_PATH; break; default: $v9643d970d1 = LIB_PATH; $v8a4df75785 = -1; } return array($v9643d970d1, substr($v327f72fb62, $v8a4df75785 + 1)); } ?>
